export interface Country {
  name: string;
  abbreviation: string;
  flagSrc: string;
  facts: {
    population: number;
    capital: string;
    area: number;
    currency: string;
  };
  geography: {
    region: string;
    subregion: string;
    borders: string[];
    isIsland: boolean;
  };
}

export const countries: Country[] = [
  {
    name: "Andorra",
    abbreviation: "ad",
    flagSrc: "/flags/ad.svg",
    facts: {
      population: 77006,
      capital: "Andorra la Vella",
      area: 468,
      currency: "Euro",
    },
    geography: {
      region: "Europe",
      subregion: "Southern Europe",
      borders: ["fr", "es"],
      isIsland: false,
    },
  },
  {
    name: "Vereinigte Arabische Emirate",
    abbreviation: "ae",
    flagSrc: "/flags/ae.svg",
    facts: {
      population: 9630959,
      capital: "Abu Dhabi",
      area: 83600,
      currency: "UAE dirham",
    },
    geography: {
      region: "Asia",
      subregion: "Western Asia",
      borders: ["sa", "om"],
      isIsland: false,
    },
  },
  {
    name: "Afghanistan",
    abbreviation: "af",
    flagSrc: "/flags/af.svg",
    facts: {
      population: 38928341,
      capital: "Kabul",
      area: 652230,
      currency: "Afghan afghani",
    },
    geography: {
      region: "Asia",
      subregion: "Southern Asia",
      borders: ["ir", "pk", "tm", "uz", "tj", "cn"],
      isIsland: false,
    },
  },
  {
    name: "Antigua und Barbuda",
    abbreviation: "ag",
    flagSrc: "/flags/ag.svg",
    facts: {
      population: 97929,
      capital: "St. John's",
      area: 442,
      currency: "East Caribbean dollar",
    },
    geography: {
      region: "Americas",
      subregion: "Caribbean",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Anguilla",
    abbreviation: "ai",
    flagSrc: "/flags/ai.svg",
    facts: {
      population: 15003,
      capital: "The Valley",
      area: 91,
      currency: "East Caribbean dollar",
    },
    geography: {
      region: "Americas",
      subregion: "Caribbean",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Albanien",
    abbreviation: "al",
    flagSrc: "/flags/al.svg",
    facts: {
      population: 2877797,
      capital: "Tirana",
      area: 28748,
      currency: "Albanian lek",
    },
    geography: {
      region: "Europe",
      subregion: "Southern Europe",
      borders: ["me", "gr", "xk", "mk"],
      isIsland: false,
    },
  },
  {
    name: "Armenien",
    abbreviation: "am",
    flagSrc: "/flags/am.svg",
    facts: {
      population: 2963243,
      capital: "Yerevan",
      area: 29743,
      currency: "Armenian dram",
    },
    geography: {
      region: "Asia",
      subregion: "Western Asia",
      borders: ["ge", "ir", "tr", "az"],
      isIsland: false,
    },
  },
  {
    name: "Angola",
    abbreviation: "ao",
    flagSrc: "/flags/ao.svg",
    facts: {
      population: 32866272,
      capital: "Luanda",
      area: 1246700,
      currency: "Angolan kwanza",
    },
    geography: {
      region: "Africa",
      subregion: "Middle Africa",
      borders: ["cd", "na", "zm", "cg"],
      isIsland: false,
    },
  },
  {
    name: "Antarktis",
    abbreviation: "aq",
    flagSrc: "/flags/aq.svg",
    facts: {
      population: 1000,
      capital: "",
      area: 14000000,
      currency: "",
    },
    geography: {
      region: "Antarctic",
      subregion: "",
      borders: [],
      isIsland: false,
    },
  },
  {
    name: "Argentinien",
    abbreviation: "ar",
    flagSrc: "/flags/ar.svg",
    facts: {
      population: 45195774,
      capital: "Buenos Aires",
      area: 2780400,
      currency: "Argentine peso",
    },
    geography: {
      region: "Americas",
      subregion: "South America",
      borders: ["bo", "br", "cl", "py", "uy"],
      isIsland: false,
    },
  },
  {
    name: "Österreich",
    abbreviation: "at",
    flagSrc: "/flags/at.svg",
    facts: {
      population: 9006398,
      capital: "Vienna",
      area: 83871,
      currency: "Euro",
    },
    geography: {
      region: "Europe",
      subregion: "Western Europe",
      borders: ["cz", "de", "hu", "it", "li", "sk", "si", "ch"],
      isIsland: false,
    },
  },
  {
    name: "Australien",
    abbreviation: "au",
    flagSrc: "/flags/au.svg",
    facts: {
      population: 25687041,
      capital: "Canberra",
      area: 7692024,
      currency: "Australian dollar",
    },
    geography: {
      region: "Oceania",
      subregion: "Australia and New Zealand",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Aruba",
    abbreviation: "aw",
    flagSrc: "/flags/aw.svg",
    facts: {
      population: 106766,
      capital: "Oranjestad",
      area: 180,
      currency: "Aruban florin",
    },
    geography: {
      region: "Americas",
      subregion: "Caribbean",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Åland",
    abbreviation: "ax",
    flagSrc: "/flags/ax.svg",
    facts: {
      population: 29458,
      capital: "Mariehamn",
      area: 1580,
      currency: "Euro",
    },
    geography: {
      region: "Europe",
      subregion: "Northern Europe",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Aserbaidschan",
    abbreviation: "az",
    flagSrc: "/flags/az.svg",
    facts: {
      population: 10139177,
      capital: "Baku",
      area: 86600,
      currency: "Azerbaijani manat",
    },
    geography: {
      region: "Asia",
      subregion: "Western Asia",
      borders: ["am", "ge", "ir", "ru", "tr"],
      isIsland: false,
    },
  },
  {
    name: "Bosnien und Herzegowina",
    abbreviation: "ba",
    flagSrc: "/flags/ba.svg",
    facts: {
      population: 3280819,
      capital: "Sarajevo",
      area: 51197,
      currency: "Bosnia and Herzegovina convertible mark",
    },
    geography: {
      region: "Europe",
      subregion: "Southern Europe",
      borders: ["hr", "me", "rs"],
      isIsland: false,
    },
  },
  {
    name: "Barbados",
    abbreviation: "bb",
    flagSrc: "/flags/bb.svg",
    facts: {
      population: 287371,
      capital: "Bridgetown",
      area: 430,
      currency: "Barbadian dollar",
    },
    geography: {
      region: "Americas",
      subregion: "Caribbean",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Bangladesch",
    abbreviation: "bd",
    flagSrc: "/flags/bd.svg",
    facts: {
      population: 164689383,
      capital: "Dhaka",
      area: 147570,
      currency: "Bangladeshi taka",
    },
    geography: {
      region: "Asia",
      subregion: "Southern Asia",
      borders: ["in", "mm"],
      isIsland: false,
    },
  },
  {
    name: "Belgien",
    abbreviation: "be",
    flagSrc: "/flags/be.svg",
    facts: {
      population: 11589623,
      capital: "Brussels",
      area: 30528,
      currency: "Euro",
    },
    geography: {
      region: "Europe",
      subregion: "Western Europe",
      borders: ["fr", "de", "lu", "nl"],
      isIsland: false,
    },
  },
  {
    name: "Burkina Faso",
    abbreviation: "bf",
    flagSrc: "/flags/bf.svg",
    facts: {
      population: 20903278,
      capital: "Ouagadougou",
      area: 272967,
      currency: "West African CFA franc",
    },
    geography: {
      region: "Africa",
      subregion: "Western Africa",
      borders: ["bj", "ci", "gh", "ml", "ne", "tg"],
      isIsland: false,
    },
  },
  {
    name: "Bulgarien",
    abbreviation: "bg",
    flagSrc: "/flags/bg.svg",
    facts: {
      population: 6948445,
      capital: "Sofia",
      area: 110879,
      currency: "Bulgarian lev",
    },
    geography: {
      region: "Europe",
      subregion: "Eastern Europe",
      borders: ["gr", "mk", "ro", "rs", "tr"],
      isIsland: false,
    },
  },
  {
    name: "Bahrain",
    abbreviation: "bh",
    flagSrc: "/flags/bh.svg",
    facts: {
      population: 1701583,
      capital: "Manama",
      area: 765,
      currency: "Bahraini dinar",
    },
    geography: {
      region: "Asia",
      subregion: "Western Asia",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Burundi",
    abbreviation: "bi",
    flagSrc: "/flags/bi.svg",
    facts: {
      population: 11890784,
      capital: "Gitega",
      area: 27834,
      currency: "Burundian franc",
    },
    geography: {
      region: "Africa",
      subregion: "Eastern Africa",
      borders: ["cd", "rw", "tz"],
      isIsland: false,
    },
  },
  {
    name: "Benin",
    abbreviation: "bj",
    flagSrc: "/flags/bj.svg",
    facts: {
      population: 12123198,
      capital: "Porto-Novo",
      area: 112622,
      currency: "West African CFA franc",
    },
    geography: {
      region: "Africa",
      subregion: "Western Africa",
      borders: ["bf", "ne", "ng", "tg"],
      isIsland: false,
    },
  },
  {
    name: "Saint-Barthélemy",
    abbreviation: "bl",
    flagSrc: "/flags/bl.svg",
    facts: {
      population: 4255,
      capital: "Gustavia",
      area: 21,
      currency: "Euro",
    },
    geography: {
      region: "Americas",
      subregion: "Caribbean",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Bermuda",
    abbreviation: "bm",
    flagSrc: "/flags/bm.svg",
    facts: {
      population: 63903,
      capital: "Hamilton",
      area: 54,
      currency: "Bermudian dollar",
    },
    geography: {
      region: "Americas",
      subregion: "Northern America",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Brunei Darussalam",
    abbreviation: "bn",
    flagSrc: "/flags/bn.svg",
    facts: {
      population: 437479,
      capital: "Bandar Seri Begawan",
      area: 5765,
      currency: "Brunei dollar",
    },
    geography: {
      region: "Asia",
      subregion: "South-Eastern Asia",
      borders: ["my"],
      isIsland: false,
    },
  },
  {
    name: "Bolivien (Plurinationaler Staat)",
    abbreviation: "bo",
    flagSrc: "/flags/bo.svg",
    facts: {
      population: 11673021,
      capital: "Sucre",
      area: 1098581,
      currency: "Boliviano",
    },
    geography: {
      region: "Americas",
      subregion: "South America",
      borders: ["ar", "br", "cl", "py", "pe"],
      isIsland: false,
    },
  },
  {
    name: "Bonaire, Sint Eustatius und Saba",
    abbreviation: "bq",
    flagSrc: "/flags/bq.svg",
    facts: {
      population: 26221,
      capital: "Kralendijk",
      area: 294,
      currency: "United States dollar",
    },
    geography: {
      region: "Americas",
      subregion: "Caribbean",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Brasilien",
    abbreviation: "br",
    flagSrc: "/flags/br.svg",
    facts: {
      population: 212559409,
      capital: "Brasília",
      area: 8515767,
      currency: "Brazilian real",
    },
    geography: {
      region: "Americas",
      subregion: "South America",
      borders: ["ar", "bo", "co", "gf", "gy", "py", "pe", "sr", "uy", "ve"],
      isIsland: false,
    },
  },
  {
    name: "Bahamas",
    abbreviation: "bs",
    flagSrc: "/flags/bs.svg",
    facts: {
      population: 393244,
      capital: "Nassau",
      area: 13943,
      currency: "Bahamian dollar",
    },
    geography: {
      region: "Americas",
      subregion: "Caribbean",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Bhutan",
    abbreviation: "bt",
    flagSrc: "/flags/bt.svg",
    facts: {
      population: 771612,
      capital: "Thimphu",
      area: 38394,
      currency: "Bhutanese ngultrum",
    },
    geography: {
      region: "Asia",
      subregion: "Southern Asia",
      borders: ["cn", "in"],
      isIsland: false,
    },
  },
  {
    name: "Botswana",
    abbreviation: "bw",
    flagSrc: "/flags/bw.svg",
    facts: {
      population: 2351627,
      capital: "Gaborone",
      area: 582000,
      currency: "Botswana pula",
    },
    geography: {
      region: "Africa",
      subregion: "Southern Africa",
      borders: ["na", "za", "zm", "zw"],
      isIsland: false,
    },
  },
  {
    name: "Belarus",
    abbreviation: "by",
    flagSrc: "/flags/by.svg",
    facts: {
      population: 9449323,
      capital: "Minsk",
      area: 207600,
      currency: "Belarusian ruble",
    },
    geography: {
      region: "Europe",
      subregion: "Eastern Europe",
      borders: ["lv", "lt", "pl", "ru", "ua"],
      isIsland: false,
    },
  },
  {
    name: "Belize",
    abbreviation: "bz",
    flagSrc: "/flags/bz.svg",
    facts: {
      population: 397621,
      capital: "Belmopan",
      area: 22966,
      currency: "Belize dollar",
    },
    geography: {
      region: "Americas",
      subregion: "Central America",
      borders: ["gt", "mx"],
      isIsland: false,
    },
  },
  {
    name: "Kanada",
    abbreviation: "ca",
    flagSrc: "/flags/ca.svg",
    facts: {
      population: 37742157,
      capital: "Ottawa",
      area: 9984670,
      currency: "Canadian dollar",
    },
    geography: {
      region: "Americas",
      subregion: "Northern America",
      borders: ["us"],
      isIsland: false,
    },
  },
  {
    name: "Kokosinseln (Keelinginseln)",
    abbreviation: "cc",
    flagSrc: "/flags/cc.svg",
    facts: {
      population: 544,
      capital: "West Island",
      area: 14,
      currency: "Australian dollar",
    },
    geography: {
      region: "Oceania",
      subregion: "Australia and New Zealand",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Demokratische Republik Kongo",
    abbreviation: "cd",
    flagSrc: "/flags/cd.svg",
    facts: {
      population: 89561403,
      capital: "Kinshasa",
      area: 2344858,
      currency: "Congolese franc",
    },
    geography: {
      region: "Africa",
      subregion: "Middle Africa",
      borders: ["ao", "bi", "cf", "cg", "rw", "ss", "tz", "ug", "zm"],
      isIsland: false,
    },
  },
  {
    name: "Zentralafrikanische Republik",
    abbreviation: "cf",
    flagSrc: "/flags/cf.svg",
    facts: {
      population: 4829767,
      capital: "Bangui",
      area: 622984,
      currency: "Central African CFA franc",
    },
    geography: {
      region: "Africa",
      subregion: "Middle Africa",
      borders: ["cm", "td", "cd", "cg", "ss", "sd"],
      isIsland: false,
    },
  },
  {
    name: "Kongo",
    abbreviation: "cg",
    flagSrc: "/flags/cg.svg",
    facts: {
      population: 5518087,
      capital: "Brazzaville",
      area: 342000,
      currency: "Central African CFA franc",
    },
    geography: {
      region: "Africa",
      subregion: "Middle Africa",
      borders: ["ao", "cm", "cf", "cd", "ga"],
      isIsland: false,
    },
  },
  {
    name: "Schweiz",
    abbreviation: "ch",
    flagSrc: "/flags/ch.svg",
    facts: {
      population: 8654622,
      capital: "Bern",
      area: 41284,
      currency: "Swiss franc",
    },
    geography: {
      region: "Europe",
      subregion: "Western Europe",
      borders: ["at", "fr", "it", "li", "de"],
      isIsland: false,
    },
  },
  {
    name: "Elfenbeinküste",
    abbreviation: "ci",
    flagSrc: "/flags/ci.svg",
    facts: {
      population: 26378275,
      capital: "Yamoussoukro",
      area: 322463,
      currency: "West African CFA franc",
    },
    geography: {
      region: "Africa",
      subregion: "Western Africa",
      borders: ["bf", "gh", "gn", "lr", "ml"],
      isIsland: false,
    },
  },
  {
    name: "Cookinseln",
    abbreviation: "ck",
    flagSrc: "/flags/ck.svg",
    facts: {
      population: 17464,
      capital: "Avarua",
      area: 236,
      currency: "New Zealand dollar",
    },
    geography: {
      region: "Oceania",
      subregion: "Polynesia",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Chile",
    abbreviation: "cl",
    flagSrc: "/flags/cl.svg",
    facts: {
      population: 19116201,
      capital: "Santiago",
      area: 756102,
      currency: "Chilean peso",
    },
    geography: {
      region: "Americas",
      subregion: "South America",
      borders: ["ar", "bo", "pe"],
      isIsland: false,
    },
  },
  {
    name: "Kamerun",
    abbreviation: "cm",
    flagSrc: "/flags/cm.svg",
    facts: {
      population: 26545863,
      capital: "Yaoundé",
      area: 475442,
      currency: "Central African CFA franc",
    },
    geography: {
      region: "Africa",
      subregion: "Middle Africa",
      borders: ["cf", "td", "cg", "gq", "ga", "ng"],
      isIsland: false,
    },
  },
  {
    name: "China",
    abbreviation: "cn",
    flagSrc: "/flags/cn.svg",
    facts: {
      population: 1402112000,
      capital: "Beijing",
      area: 9640011,
      currency: "Chinese yuan",
    },
    geography: {
      region: "Asia",
      subregion: "Eastern Asia",
      borders: ["af", "bt", "in", "kz", "kp", "kg", "la", "mn", "mm", "np", "pk", "ru", "vn"],
      isIsland: false,
    },
  },
  {
    name: "Kolumbien",
    abbreviation: "co",
    flagSrc: "/flags/co.svg",
    facts: {
      population: 50882891,
      capital: "Bogotá",
      area: 1141748,
      currency: "Colombian peso",
    },
    geography: {
      region: "Americas",
      subregion: "South America",
      borders: ["br", "ec", "pa", "pe", "ve"],
      isIsland: false,
    },
  },
  {
    name: "Costa Rica",
    abbreviation: "cr",
    flagSrc: "/flags/cr.svg",
    facts: {
      population: 5094118,
      capital: "San José",
      area: 51100,
      currency: "Costa Rican colón",
    },
    geography: {
      region: "Americas",
      subregion: "Central America",
      borders: ["ni", "pa"],
      isIsland: false,
    },
  },
  {
    name: "Kuba",
    abbreviation: "cu",
    flagSrc: "/flags/cu.svg",
    facts: {
      population: 11326616,
      capital: "Havana",
      area: 109884,
      currency: "Cuban convertible peso",
    },
    geography: {
      region: "Americas",
      subregion: "Caribbean",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Kap Verde",
    abbreviation: "cv",
    flagSrc: "/flags/cv.svg",
    facts: {
      population: 555988,
      capital: "Praia",
      area: 4033,
      currency: "Cape Verdean escudo",
    },
    geography: {
      region: "Africa",
      subregion: "Western Africa",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Curaçao",
    abbreviation: "cw",
    flagSrc: "/flags/cw.svg",
    facts: {
      population: 155014,
      capital: "Willemstad",
      area: 444,
      currency: "Netherlands Antillean guilder",
    },
    geography: {
      region: "Americas",
      subregion: "Caribbean",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Weihnachtsinsel",
    abbreviation: "cx",
    flagSrc: "/flags/cx.svg",
    facts: {
      population: 2072,
      capital: "Flying Fish Cove",
      area: 135,
      currency: "Australian dollar",
    },
    geography: {
      region: "Oceania",
      subregion: "Australia and New Zealand",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Zypern",
    abbreviation: "cy",
    flagSrc: "/flags/cy.svg",
    facts: {
      population: 1207359,
      capital: "Nicosia",
      area: 9251,
      currency: "Euro",
    },
    geography: {
      region: "Asia",
      subregion: "Western Asia",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Tschechische Republik",
    abbreviation: "cz",
    flagSrc: "/flags/cz.svg",
    facts: {
      population: 10708981,
      capital: "Prague",
      area: 78865,
      currency: "Czech koruna",
    },
    geography: {
      region: "Europe",
      subregion: "Eastern Europe",
      borders: ["at", "de", "pl", "sk"],
      isIsland: false,
    },
  },
  {
    name: "Deutschland",
    abbreviation: "de",
    flagSrc: "/flags/de.svg",
    facts: {
      population: 83240525,
      capital: "Berlin",
      area: 357114,
      currency: "Euro",
    },
    geography: {
      region: "Europe",
      subregion: "Western Europe",
      borders: ["at", "be", "cz", "dk", "fr", "lu", "nl", "pl", "ch"],
      isIsland: false,
    },
  },
  {
    name: "Dschibuti",
    abbreviation: "dj",
    flagSrc: "/flags/dj.svg",
    facts: {
      population: 988000,
      capital: "Djibouti",
      area: 23200,
      currency: "Djiboutian franc",
    },
    geography: {
      region: "Africa",
      subregion: "Eastern Africa",
      borders: ["er", "et", "so"],
      isIsland: false,
    },
  },
  {
    name: "Dänemark",
    abbreviation: "dk",
    flagSrc: "/flags/dk.svg",
    facts: {
      population: 5831404,
      capital: "Copenhagen",
      area: 43094,
      currency: "Danish krone",
    },
    geography: {
      region: "Europe",
      subregion: "Northern Europe",
      borders: ["de"],
      isIsland: false,
    },
  },
  {
    name: "Dominica",
    abbreviation: "dm",
    flagSrc: "/flags/dm.svg",
    facts: {
      population: 71991,
      capital: "Roseau",
      area: 751,
      currency: "East Caribbean dollar",
    },
    geography: {
      region: "Americas",
      subregion: "Caribbean",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Dominikanische Republik",
    abbreviation: "do",
    flagSrc: "/flags/do.svg",
    facts: {
      population: 10847904,
      capital: "Santo Domingo",
      area: 48671,
      currency: "Dominican peso",
    },
    geography: {
      region: "Americas",
      subregion: "Caribbean",
      borders: ["ht"],
      isIsland: false,
    },
  },
  {
    name: "Algerien",
    abbreviation: "dz",
    flagSrc: "/flags/dz.svg",
    facts: {
      population: 43851044,
      capital: "Algiers",
      area: 2381741,
      currency: "Algerian dinar",
    },
    geography: {
      region: "Africa",
      subregion: "Northern Africa",
      borders: ["tn", "ly", "ne", "mr", "ml", "ma", "eh"],
      isIsland: false,
    },
  },
  {
    name: "Ecuador",
    abbreviation: "ec",
    flagSrc: "/flags/ec.svg",
    facts: {
      population: 17643060,
      capital: "Quito",
      area: 276841,
      currency: "United States dollar",
    },
    geography: {
      region: "Americas",
      subregion: "South America",
      borders: ["co", "pe"],
      isIsland: false,
    },
  },
  {
    name: "Estland",
    abbreviation: "ee",
    flagSrc: "/flags/ee.svg",
    facts: {
      population: 1326535,
      capital: "Tallinn",
      area: 45227,
      currency: "Euro",
    },
    geography: {
      region: "Europe",
      subregion: "Northern Europe",
      borders: ["lv", "ru"],
      isIsland: false,
    },
  },
  {
    name: "Ägypten",
    abbreviation: "eg",
    flagSrc: "/flags/eg.svg",
    facts: {
      population: 102334404,
      capital: "Cairo",
      area: 1002450,
      currency: "Egyptian pound",
    },
    geography: {
      region: "Africa",
      subregion: "Northern Africa",
      borders: ["il", "ly", "sd"],
      isIsland: false,
    },
  },
  {
    name: "Westsahara",
    abbreviation: "eh",
    flagSrc: "/flags/eh.svg",
    facts: {
      population: 597339,
      capital: "El Aaiún",
      area: 266000,
      currency: "Moroccan dirham",
    },
    geography: {
      region: "Africa",
      subregion: "Northern Africa",
      borders: ["dz", "mr", "ma"],
      isIsland: false,
    },
  },
  {
    name: "Eritrea",
    abbreviation: "er",
    flagSrc: "/flags/er.svg",
    facts: {
      population: 3546421,
      capital: "Asmara",
      area: 117600,
      currency: "Eritrean nakfa",
    },
    geography: {
      region: "Africa",
      subregion: "Eastern Africa",
      borders: ["dj", "et", "sd"],
      isIsland: false,
    },
  },
  {
    name: "Spanien",
    abbreviation: "es",
    flagSrc: "/flags/es.svg",
    facts: {
      population: 47351567,
      capital: "Madrid",
      area: 505992,
      currency: "Euro",
    },
    geography: {
      region: "Europe",
      subregion: "Southern Europe",
      borders: ["ad", "fr", "gi", "pt", "ma"],
      isIsland: false,
    },
  },
  {
    name: "Estland",
    abbreviation: "et",
    flagSrc: "/flags/et.svg",
    facts: {
      population: 114963588,
      capital: "Addis Ababa",
      area: 1104300,
      currency: "Ethiopian birr",
    },
    geography: {
      region: "Africa",
      subregion: "Eastern Africa",
      borders: ["dj", "er", "ke", "so", "ss", "sd"],
      isIsland: false,
    },
  },
  {
    name: "Finnland",
    abbreviation: "fi",
    flagSrc: "/flags/fi.svg",
    facts: {
      population: 5540720,
      capital: "Helsinki",
      area: 338424,
      currency: "Euro",
    },
    geography: {
      region: "Europe",
      subregion: "Northern Europe",
      borders: ["no", "se", "ru"],
      isIsland: false,
    },
  },
  {
    name: "Fidschi",
    abbreviation: "fj",
    flagSrc: "/flags/fj.svg",
    facts: {
      population: 896445,
      capital: "Suva",
      area: 18274,
      currency: "Fijian dollar",
    },
    geography: {
      region: "Oceania",
      subregion: "Melanesia",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Mikronesien (föderierte Staaten)",
    abbreviation: "fm",
    flagSrc: "/flags/fm.svg",
    facts: {
      population: 548914,
      capital: "Palikir",
      area: 701,
      currency: "United States dollar",
    },
    geography: {
      region: "Oceania",
      subregion: "Micronesia",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Färöer",
    abbreviation: "fo",
    flagSrc: "/flags/fo.svg",
    facts: {
      population: 48863,
      capital: "Tórshavn",
      area: 1393,
      currency: "Danish krone",
    },
    geography: {
      region: "Europe",
      subregion: "Northern Europe",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Frankreich",
    abbreviation: "fr",
    flagSrc: "/flags/fr.svg",
    facts: {
      population: 67391582,
      capital: "Paris",
      area: 551695,
      currency: "Euro",
    },
    geography: {
      region: "Europe",
      subregion: "Western Europe",
      borders: ["ad", "be", "de", "it", "lu", "mc", "es", "ch"],
      isIsland: false,
    },
  },
  {
    name: "Gabun",
    abbreviation: "ga",
    flagSrc: "/flags/ga.svg",
    facts: {
      population: 2225734,
      capital: "Libreville",
      area: 267668,
      currency: "Central African CFA franc",
    },
    geography: {
      region: "Africa",
      subregion: "Middle Africa",
      borders: ["cm", "cg", "gq"],
      isIsland: false,
    },
  },
  {
    name: "Vereinigtes Königreich Großbritannien und Nordirland",
    abbreviation: "gb",
    flagSrc: "/flags/gb.svg",
    facts: {
      population: 67886004,
      capital: "London",
      area: 243610,
      currency: "British pound",
    },
    geography: {
      region: "Europe",
      subregion: "Northern Europe",
      borders: ["ie"],
      isIsland: false,
    },
  },
  {
    name: "Grenada",
    abbreviation: "gd",
    flagSrc: "/flags/gd.svg",
    facts: {
      population: 112519,
      capital: "St. George's",
      area: 344,
      currency: "East Caribbean dollar",
    },
    geography: {
      region: "Americas",
      subregion: "Caribbean",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Georgien",
    abbreviation: "ge",
    flagSrc: "/flags/ge.svg",
    facts: {
      population: 3989167,
      capital: "Tbilisi",
      area: 69700,
      currency: "Georgian lari",
    },
    geography: {
      region: "Asia",
      subregion: "Western Asia",
      borders: ["am", "az", "ru", "tr"],
      isIsland: false,
    },
  },
  {
    name: "Französisch-Guayana",
    abbreviation: "gf",
    flagSrc: "/flags/gf.svg",
    facts: {
      population: 298682,
      capital: "Cayenne",
      area: 83534,
      currency: "Euro",
    },
    geography: {
      region: "Americas",
      subregion: "South America",
      borders: ["br", "sr"],
      isIsland: false,
    },
  },
  {
    name: "Guernsey",
    abbreviation: "gg",
    flagSrc: "/flags/gg.svg",
    facts: {
      population: 62999,
      capital: "St. Peter Port",
      area: 78,
      currency: "British pound",
    },
    geography: {
      region: "Europe",
      subregion: "Northern Europe",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Ghana",
    abbreviation: "gh",
    flagSrc: "/flags/gh.svg",
    facts: {
      population: 31072940,
      capital: "Accra",
      area: 238533,
      currency: "Ghanaian cedi",
    },
    geography: {
      region: "Africa",
      subregion: "Western Africa",
      borders: ["bf", "ci", "tg"],
      isIsland: false,
    },
  },
  {
    name: "Gibraltar",
    abbreviation: "gi",
    flagSrc: "/flags/gi.svg",
    facts: {
      population: 33691,
      capital: "Gibraltar",
      area: 6,
      currency: "Gibraltar pound",
    },
    geography: {
      region: "Europe",
      subregion: "Southern Europe",
      borders: ["es"],
      isIsland: false,
    },
  },
  {
    name: "Grönland",
    abbreviation: "gl",
    flagSrc: "/flags/gl.svg",
    facts: {
      population: 56367,
      capital: "Nuuk",
      area: 2166086,
      currency: "Danish krone",
    },
    geography: {
      region: "Americas",
      subregion: "North America",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Gambia",
    abbreviation: "gm",
    flagSrc: "/flags/gm.svg",
    facts: {
      population: 2416668,
      capital: "Banjul",
      area: 11295,
      currency: "Gambian dalasi",
    },
    geography: {
      region: "Africa",
      subregion: "Western Africa",
      borders: ["sn"],
      isIsland: false,
    },
  },
  {
    name: "Guinea",
    abbreviation: "gn",
    flagSrc: "/flags/gn.svg",
    facts: {
      population: 13132792,
      capital: "Conakry",
      area: 245857,
      currency: "Guinean franc",
    },
    geography: {
      region: "Africa",
      subregion: "Western Africa",
      borders: ["ci", "gw", "lr", "ml", "sn", "sl"],
      isIsland: false,
    },
  },
  {
    name: "Äquatorialguinea",
    abbreviation: "gq",
    flagSrc: "/flags/gq.svg",
    facts: {
      population: 1402985,
      capital: "Malabo",
      area: 28051,
      currency: "Central African CFA franc",
    },
    geography: {
      region: "Africa",
      subregion: "Middle Africa",
      borders: ["cm", "ga"],
      isIsland: false,
    },
  },
  {
    name: "Griechenland",
    abbreviation: "gr",
    flagSrc: "/flags/gr.svg",
    facts: {
      population: 10715549,
      capital: "Athens",
      area: 131990,
      currency: "Euro",
    },
    geography: {
      region: "Europe",
      subregion: "Southern Europe",
      borders: ["al", "bg", "tr", "mk"],
      isIsland: false,
    },
  },
  {
    name: "Guatemala",
    abbreviation: "gt",
    flagSrc: "/flags/gt.svg",
    facts: {
      population: 17915567,
      capital: "Guatemala City",
      area: 108889,
      currency: "Guatemalan quetzal",
    },
    geography: {
      region: "Americas",
      subregion: "Central America",
      borders: ["bz", "sv", "hn", "mx"],
      isIsland: false,
    },
  },
  {
    name: "Guam",
    abbreviation: "gu",
    flagSrc: "/flags/gu.svg",
    facts: {
      population: 168775,
      capital: "Hagåtña",
      area: 549,
      currency: "United States dollar",
    },
    geography: {
      region: "Oceania",
      subregion: "Micronesia",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Guinea-Bissau",
    abbreviation: "gw",
    flagSrc: "/flags/gw.svg",
    facts: {
      population: 1968001,
      capital: "Bissau",
      area: 36125,
      currency: "West African CFA franc",
    },
    geography: {
      region: "Africa",
      subregion: "Western Africa",
      borders: ["gn", "sn"],
      isIsland: false,
    },
  },
  {
    name: "Guyana",
    abbreviation: "gy",
    flagSrc: "/flags/gy.svg",
    facts: {
      population: 786552,
      capital: "Georgetown",
      area: 214969,
      currency: "Guyanese dollar",
    },
    geography: {
      region: "Americas",
      subregion: "South America",
      borders: ["br", "sr", "ve"],
      isIsland: false,
    },
  },
  {
    name: "Hongkong",
    abbreviation: "hk",
    flagSrc: "/flags/hk.svg",
    facts: {
      population: 7500700,
      capital: "City of Victoria",
      area: 1104,
      currency: "Hong Kong dollar",
    },
    geography: {
      region: "Asia",
      subregion: "Eastern Asia",
      borders: ["cn"],
      isIsland: false,
    },
  },
  {
    name: "Honduras",
    abbreviation: "hn",
    flagSrc: "/flags/hn.svg",
    facts: {
      population: 9904607,
      capital: "Tegucigalpa",
      area: 112492,
      currency: "Honduran lempira",
    },
    geography: {
      region: "Americas",
      subregion: "Central America",
      borders: ["gt", "sv", "ni"],
      isIsland: false,
    },
  },
  {
    name: "Kroatien",
    abbreviation: "hr",
    flagSrc: "/flags/hr.svg",
    facts: {
      population: 4047200,
      capital: "Zagreb",
      area: 56594,
      currency: "Croatian kuna",
    },
    geography: {
      region: "Europe",
      subregion: "Southern Europe",
      borders: ["ba", "hu", "me", "rs", "si"],
      isIsland: false,
    },
  },
  {
    name: "Haiti",
    abbreviation: "ht",
    flagSrc: "/flags/ht.svg",
    facts: {
      population: 11402533,
      capital: "Port-au-Prince",
      area: 27750,
      currency: "Haitian gourde",
    },
    geography: {
      region: "Americas",
      subregion: "Caribbean",
      borders: ["do"],
      isIsland: false,
    },
  },
  {
    name: "Ungarn",
    abbreviation: "hu",
    flagSrc: "/flags/hu.svg",
    facts: {
      population: 9721559,
      capital: "Budapest",
      area: 93028,
      currency: "Hungarian forint",
    },
    geography: {
      region: "Europe",
      subregion: "Eastern Europe",
      borders: ["at", "hr", "ro", "rs", "sk", "si", "ua"],
      isIsland: false,
    },
  },
  {
    name: "Indonesien",
    abbreviation: "id",
    flagSrc: "/flags/id.svg",
    facts: {
      population: 273523621,
      capital: "Jakarta",
      area: 1904569,
      currency: "Indonesian rupiah",
    },
    geography: {
      region: "Asia",
      subregion: "South-Eastern Asia",
      borders: ["tl", "my", "pg"],
      isIsland: false,
    },
  },
  {
    name: "Irland",
    abbreviation: "ie",
    flagSrc: "/flags/ie.svg",
    facts: {
      population: 4994724,
      capital: "Dublin",
      area: 70273,
      currency: "Euro",
    },
    geography: {
      region: "Europe",
      subregion: "Northern Europe",
      borders: ["gb"],
      isIsland: false,
    },
  },
  {
    name: "Israel",
    abbreviation: "il",
    flagSrc: "/flags/il.svg",
    facts: {
      population: 9216900,
      capital: "Jerusalem",
      area: 20770,
      currency: "Israeli new shekel",
    },
    geography: {
      region: "Asia",
      subregion: "Western Asia",
      borders: ["eg", "jo", "lb", "sy"],
      isIsland: false,
    },
  },
  {
    name: "Indien",
    abbreviation: "in",
    flagSrc: "/flags/in.svg",
    facts: {
      population: 1380004385,
      capital: "New Delhi",
      area: 3287590,
      currency: "Indian rupee",
    },
    geography: {
      region: "Asia",
      subregion: "Southern Asia",
      borders: ["bd", "bt", "mm", "cn", "np", "pk", "lk"],
      isIsland: false,
    },
  },
  {
    name: "Irak",
    abbreviation: "iq",
    flagSrc: "/flags/iq.svg",
    facts: {
      population: 40222493,
      capital: "Baghdad",
      area: 438317,
      currency: "Iraqi dinar",
    },
    geography: {
      region: "Asia",
      subregion: "Western Asia",
      borders: ["ir", "jo", "kw", "sa", "sy", "tr"],
      isIsland: false,
    },
  },
  {
    name: "Iran",
    abbreviation: "ir",
    flagSrc: "/flags/ir.svg",
    facts: {
      population: 83992949,
      capital: "Tehran",
      area: 1648195,
      currency: "Iranian rial",
    },
    geography: {
      region: "Asia",
      subregion: "Southern Asia",
      borders: ["af", "am", "az", "iq", "pk", "tr", "tm"],
      isIsland: false,
    },
  },
  {
    name: "Island",
    abbreviation: "is",
    flagSrc: "/flags/is.svg",
    facts: {
      population: 366425,
      capital: "Reykjavik",
      area: 103000,
      currency: "Icelandic króna",
    },
    geography: {
      region: "Europe",
      subregion: "Northern Europe",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Italien",
    abbreviation: "it",
    flagSrc: "/flags/it.svg",
    facts: {
      population: 60244639,
      capital: "Rome",
      area: 301336,
      currency: "Euro",
    },
    geography: {
      region: "Europe",
      subregion: "Southern Europe",
      borders: ["at", "fr", "sm", "si", "ch", "va"],
      isIsland: false,
    },
  },
  {
    name: "Jersey",
    abbreviation: "je",
    flagSrc: "/flags/je.svg",
    facts: {
      population: 101073,
      capital: "Saint Helier",
      area: 116,
      currency: "British pound",
    },
    geography: {
      region: "Europe",
      subregion: "Northern Europe",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Jamaika",
    abbreviation: "jm",
    flagSrc: "/flags/jm.svg",
    facts: {
      population: 2961161,
      capital: "Kingston",
      area: 10991,
      currency: "Jamaican dollar",
    },
    geography: {
      region: "Americas",
      subregion: "Caribbean",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Jordanien",
    abbreviation: "jo",
    flagSrc: "/flags/jo.svg",
    facts: {
      population: 10203134,
      capital: "Amman",
      area: 89342,
      currency: "Jordanian dinar",
    },
    geography: {
      region: "Asia",
      subregion: "Western Asia",
      borders: ["iq", "il", "sa", "sy"],
      isIsland: false,
    },
  },
  {
    name: "Japan",
    abbreviation: "jp",
    flagSrc: "/flags/jp.svg",
    facts: {
      population: 126476458,
      capital: "Tokyo",
      area: 377930,
      currency: "Yen",
    },
    geography: {
      region: "Asia",
      subregion: "Eastern Asia",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Kasachstan",
    abbreviation: "kz",
    flagSrc: "/flags/kz.svg",
    facts: {
      population: 18776707,
      capital: "Nur-Sultan",
      area: 2724900,
      currency: "Kazakhstani tenge",
    },
    geography: {
      region: "Asia",
      subregion: "Central Asia",
      borders: ["cn", "kg", "ru", "tm", "uz"],
      isIsland: false,
    },
  },
  {
    name: "Kenia",
    abbreviation: "ke",
    flagSrc: "/flags/ke.svg",
    facts: {
      population: 53771300,
      capital: "Nairobi",
      area: 580367,
      currency: "Kenyan shilling",
    },
    geography: {
      region: "Africa",
      subregion: "Eastern Africa",
      borders: ["et", "so", "ss", "tz", "ug"],
      isIsland: false,
    },
  },
  {
    name: "Kirgisistan",
    abbreviation: "kg",
    flagSrc: "/flags/kg.svg",
    facts: {
      population: 6524191,
      capital: "Bishkek",
      area: 199951,
      currency: "Kyrgyzstani som",
    },
    geography: {
      region: "Asia",
      subregion: "Central Asia",
      borders: ["cn", "kz", "tj", "uz"],
      isIsland: false,
    },
  },
  {
    name: "Kambodscha",
    abbreviation: "kh",
    flagSrc: "/flags/kh.svg",
    facts: {
      population: 16718971,
      capital: "Phnom Penh",
      area: 181035,
      currency: "Cambodian riel",
    },
    geography: {
      region: "Asia",
      subregion: "South-Eastern Asia",
      borders: ["la", "th", "vn"],
      isIsland: false,
    },
  },
  {
    name: "Kiribati",
    abbreviation: "ki",
    flagSrc: "/flags/ki.svg",
    facts: {
      population: 119446,
      capital: "South Tarawa",
      area: 811,
      currency: "Australian dollar",
    },
    geography: {
      region: "Oceania",
      subregion: "Micronesia",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Komoren",
    abbreviation: "km",
    flagSrc: "/flags/km.svg",
    facts: {
      population: 869601,
      capital: "Moroni",
      area: 2235,
      currency: "Comorian franc",
    },
    geography: {
      region: "Africa",
      subregion: "Eastern Africa",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "St. Kitts und Nevis",
    abbreviation: "kn",
    flagSrc: "/flags/kn.svg",
    facts: {
      population: 53192,
      capital: "Basseterre",
      area: 261,
      currency: "East Caribbean dollar",
    },
    geography: {
      region: "Americas",
      subregion: "Caribbean",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Nordkorea",
    abbreviation: "kp",
    flagSrc: "/flags/kp.svg",
    facts: {
      population: 25778815,
      capital: "Pyongyang",
      area: 120538,
      currency: "North Korean won",
    },
    geography: {
      region: "Asia",
      subregion: "Eastern Asia",
      borders: ["cn", "kr", "ru"],
      isIsland: false,
    },
  },
  {
    name: "Südkorea",
    abbreviation: "kr",
    flagSrc: "/flags/kr.svg",
    facts: {
      population: 51269185,
      capital: "Seoul",
      area: 100210,
      currency: "South Korean won",
    },
    geography: {
      region: "Asia",
      subregion: "Eastern Asia",
      borders: ["kp"],
      isIsland: false,
    },
  },
  {
    name: "Kuwait",
    abbreviation: "kw",
    flagSrc: "/flags/kw.svg",
    facts: {
      population: 4270563,
      capital: "Kuwait City",
      area: 17818,
      currency: "Kuwaiti dinar",
    },
    geography: {
      region: "Asia",
      subregion: "Western Asia",
      borders: ["iq", "sa"],
      isIsland: false,
    },
  },
  {
    name: "Kasachstan",
    abbreviation: "kz",
    flagSrc: "/flags/kz.svg",
    facts: {
      population: 18776707,
      capital: "Nur-Sultan",
      area: 2724900,
      currency: "Kazakhstani tenge",
    },
    geography: {
      region: "Asia",
      subregion: "Central Asia",
      borders: ["cn", "kg", "ru", "tm", "uz"],
      isIsland: false,
    },
  },
  {
    name: "Laos",
    abbreviation: "la",
    flagSrc: "/flags/la.svg",
    facts: {
      population: 7275556,
      capital: "Vientiane",
      area: 236800,
      currency: "Lao kip",
    },
    geography: {
      region: "Asia",
      subregion: "South-Eastern Asia",
      borders: ["mm", "kh", "cn", "th", "vn"],
      isIsland: false,
    },
  },
  {
    name: "Libanon",
    abbreviation: "lb",
    flagSrc: "/flags/lb.svg",
    facts: {
      population: 6856000,
      capital: "Beirut",
      area: 10452,
      currency: "Lebanese Pound (LBP)",
    },
    geography: {
      region: "Asia",
      subregion: "Western Asia",
      borders: ["il", "sy"],
      isIsland: false,
    },
  },
  {
    name: "Saint Lucia",
    abbreviation: "lc",
    flagSrc: "/flags/lc.svg",
    facts: {
      population: 184000,
      capital: "Castries",
      area: 617,
      currency: "Ostkaribischer Dollar (XCD)",
    },
    geography: {
      region: "Amerika",
      subregion: "Karibik",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Liechtenstein",
    abbreviation: "li",
    flagSrc: "/flags/li.svg",
    facts: {
      population: 38128,
      capital: "Vaduz",
      area: 160,
      currency: "Schweizer Franken (CHF)",
    },
    geography: {
      region: "Europa",
      subregion: "Westeuropa",
      borders: ["ch", "at"],
      isIsland: false,
    },
  },
  {
    name: "Sri Lanka",
    abbreviation: "lk",
    flagSrc: "/flags/lk.svg",
    facts: {
      population: 21803000,
      capital: "Colombo",
      area: 65610,
      currency: "Sri-Lanka-Rupie (LKR)",
    },
    geography: {
      region: "Asien",
      subregion: "Südasien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Liberia",
    abbreviation: "lr",
    flagSrc: "/flags/lr.svg",
    facts: {
      population: 4475353,
      capital: "Monrovia",
      area: 111369,
      currency: "Liberianischer Dollar (LRD)",
    },
    geography: {
      region: "Afrika",
      subregion: "Westafrika",
      borders: ["ci", "gn", "sl"],
      isIsland: false,
    },
  },
  {
    name: "Lesotho",
    abbreviation: "ls",
    flagSrc: "/flags/ls.svg",
    facts: {
      population: 2007201,
      capital: "Maseru",
      area: 30355,
      currency: "Loti und Südafrikanischer Rand (LSL, ZAR)",
    },
    geography: {
      region: "Afrika",
      subregion: "Südliches Afrika",
      borders: ["za"],
      isIsland: false,
    },
  },
  {
    name: "Lithuania",
    abbreviation: "lt",
    flagSrc: "/flags/lt.svg",
    facts: {
      population: 2793471,
      capital: "Vilnius",
      area: 65300,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Europa",
      subregion: "Osteuropa",
      borders: ["lv", "by", "pl", "ru"],
      isIsland: false,
    },
  },
  {
    name: "Luxembourg",
    abbreviation: "lu",
    flagSrc: "/flags/lu.svg",
    facts: {
      population: 634814,
      capital: "Luxembourg",
      area: 2586,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Europa",
      subregion: "Westeuropa",
      borders: ["be", "de", "fr"],
      isIsland: false,
    },
  },
  {
    name: "Latvia",
    abbreviation: "lv",
    flagSrc: "/flags/lv.svg",
    facts: {
      population: 1886198,
      capital: "Riga",
      area: 64562,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Europa",
      subregion: "Osteuropa",
      borders: ["ee", "lt", "by", "ru"],
      isIsland: false,
    },
  },
  {
    name: "Libya",
    abbreviation: "ly",
    flagSrc: "/flags/ly.svg",
    facts: {
      population: 6871292,
      capital: "Tripoli",
      area: 1759540,
      currency: "Libyscher Dinar (LYD)",
    },
    geography: {
      region: "Afrika",
      subregion: "Nordafrika",
      borders: ["dz", "td", "ne", "eg", "sd", "tn"],
      isIsland: false,
    },
  },
  {
    name: "Morocco",
    abbreviation: "ma",
    flagSrc: "/flags/ma.svg",
    facts: {
      population: 36910560,
      capital: "Rabat",
      area: 446550,
      currency: "Marokkanischer Dirham (MAD)",
    },
    geography: {
      region: "Afrika",
      subregion: "Nordafrika",
      borders: ["dz", "eh", "es"],
      isIsland: false,
    },
  },
  {
    name: "Monaco",
    abbreviation: "mc",
    flagSrc: "/flags/mc.svg",
    facts: {
      population: 39242,
      capital: "Monaco",
      area: 2.02,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Europa",
      subregion: "Westeuropa",
      borders: ["fr"],
      isIsland: false,
    },
  },
  {
    name: "Moldova",
    abbreviation: "md",
    flagSrc: "/flags/md.svg",
    facts: {
      population: 2657637,
      capital: "Chisinau",
      area: 33846,
      currency: "Moldauischer Leu (MDL)",
    },
    geography: {
      region: "Europa",
      subregion: "Osteuropa",
      borders: ["ro", "ua"],
      isIsland: false,
    },
  },
  {
    name: "Montenegro",
    abbreviation: "me",
    flagSrc: "/flags/me.svg",
    facts: {
      population: 622359,
      capital: "Podgorica",
      area: 13812,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Europa",
      subregion: "Südeuropa",
      borders: ["al", "ba", "hr", "rs"],
      isIsland: false,
    },
  },
  {
    name: "Saint Martin (French part)",
    abbreviation: "mf",
    flagSrc: "/flags/mf.svg",
    facts: {
      population: 36979,
      capital: "Marigot",
      area: 53.2,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Amerika",
      subregion: "Karibik",
      borders: ["sx", "nl"],
      isIsland: false,
    },
  },
  {
    name: "Madagascar",
    abbreviation: "mg",
    flagSrc: "/flags/mg.svg",
    facts: {
      population: 27691018,
      capital: "Antananarivo",
      area: 587041,
      currency: "Madagassischer Ariary (MGA)",
    },
    geography: {
      region: "Afrika",
      subregion: "Ostafrika",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Marshall Islands",
    abbreviation: "mh",
    flagSrc: "/flags/mh.svg",
    facts: {
      population: 58791,
      capital: "Majuro",
      area: 181,
      currency: "US-Dollar (USD)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Mikronesien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Macedonia (the former Yugoslav Republic of)",
    abbreviation: "mk",
    flagSrc: "/flags/mk.svg",
    facts: {
      population: 2077132,
      capital: "Skopje",
      area: 25713,
      currency: "Mazedonischer Denar (MKD)",
    },
    geography: {
      region: "Europa",
      subregion: "Südosteuropa",
      borders: ["al", "bg", "gr", "rs"],
      isIsland: false,
    },
  },
  {
    name: "Mali",
    abbreviation: "ml",
    flagSrc: "/flags/ml.svg",
    facts: {
      population: 20250833,
      capital: "Bamako",
      area: 1240192,
      currency: "CFA-Franc (XOF)",
    },
    geography: {
      region: "Afrika",
      subregion: "Westafrika",
      borders: ["dz", "bf", "ne", "sn", "gm", "gn", "ci", "bf"],
      isIsland: false,
    },
  },
  {
    name: "Malta",
    abbreviation: "mt",
    flagSrc: "/flags/mt.svg",
    facts: {
      population: 514564,
      capital: "Valletta",
      area: 316,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Europa",
      subregion: "Südeuropa",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Myanmar",
    abbreviation: "mm",
    flagSrc: "/flags/mm.svg",
    facts: {
      population: 54409800,
      capital: "Naypyidaw",
      area: 676578,
      currency: "Myanmarischer Kyat (MMK)",
    },
    geography: {
      region: "Asien",
      subregion: "Südostasien",
      borders: ["bd", "cn", "in", "la", "th"],
      isIsland: false,
    },
  },
  {
    name: "Montenegro",
    abbreviation: "me",
    flagSrc: "/flags/me.svg",
    facts: {
      population: 622359,
      capital: "Podgorica",
      area: 13812,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Europa",
      subregion: "Südeuropa",
      borders: ["al", "ba", "hr", "rs"],
      isIsland: false,
    },
  },
  {
    name: "Mongolia",
    abbreviation: "mn",
    flagSrc: "/flags/mn.svg",
    facts: {
      population: 3225167,
      capital: "Ulan-Bator",
      area: 1564110,
      currency: "Mongolischer Tögrög (MNT)",
    },
    geography: {
      region: "Asien",
      subregion: "Ostasien",
      borders: ["cn", "ru"],
      isIsland: false,
    },
  },
  {
    name: "Northern Mariana Islands",
    abbreviation: "mp",
    flagSrc: "/flags/mp.svg",
    facts: {
      population: 57559,
      capital: "Saipan",
      area: 464,
      currency: "US-Dollar (USD)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Mikronesien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Mozambique",
    abbreviation: "mz",
    flagSrc: "/flags/mz.svg",
    facts: {
      population: 31255435,
      capital: "Maputo",
      area: 801590,
      currency: "Mosambikanischer Metical (MZN)",
    },
    geography: {
      region: "Afrika",
      subregion: "Ostafrika",
      borders: ["sz", "za", "tz", "zm", "zw"],
      isIsland: false,
    },
  },
  {
    name: "Mauritania",
    abbreviation: "mr",
    flagSrc: "/flags/mr.svg",
    facts: {
      population: 4403319,
      capital: "Nouakchott",
      area: 1030700,
      currency: "Ouguiya (MRU)",
    },
    geography: {
      region: "Afrika",
      subregion: "Westafrika",
      borders: ["dz", "ml", "sn", "eh"],
      isIsland: false,
    },
  },
  {
    name: "Montserrat",
    abbreviation: "ms",
    flagSrc: "/flags/ms.svg",
    facts: {
      population: 4992,
      capital: "Plymouth (de jure), Brades (de facto)",
      area: 102,
      currency: "Ostkaribischer Dollar (XCD)",
    },
    geography: {
      region: "Amerika",
      subregion: "Karibik",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Martinique",
    abbreviation: "mq",
    flagSrc: "/flags/mq.svg",
    facts: {
      population: 376480,
      capital: "Fort-de-France",
      area: 1128,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Amerika",
      subregion: "Karibik",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Mauritius",
    abbreviation: "mu",
    flagSrc: "/flags/mu.svg",
    facts: {
      population: 1271768,
      capital: "Port Louis",
      area: 2040,
      currency: "Mauritius-Rupie (MUR)",
    },
    geography: {
      region: "Afrika",
      subregion: "Ostafrika",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Maldives",
    abbreviation: "mv",
    flagSrc: "/flags/mv.svg",
    facts: {
      population: 515696,
      capital: "Malé",
      area: 300,
      currency: "Malediven-Rufiyaa (MVR)",
    },
    geography: {
      region: "Asien",
      subregion: "Südasien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Malawi",
    abbreviation: "mw",
    flagSrc: "/flags/mw.svg",
    facts: {
      population: 19129952,
      capital: "Lilongwe",
      area: 118484,
      currency: "Malawischer Kwacha (MWK)",
    },
    geography: {
      region: "Afrika",
      subregion: "Ostafrika",
      borders: ["mz", "tz", "zm"],
      isIsland: false,
    },
  },
  {
    name: "Mexico",
    abbreviation: "mx",
    flagSrc: "/flags/mx.svg",
    facts: {
      population: 126190788,
      capital: "Mexiko-Stadt",
      area: 1964375,
      currency: "Mexikanischer Peso (MXN)",
    },
    geography: {
      region: "Amerika",
      subregion: "Zentralamerika",
      borders: ["bz", "gt", "us"],
      isIsland: false,
    },
  },
  {
    name: "Malaysia",
    abbreviation: "my",
    flagSrc: "/flags/my.svg",
    facts: {
      population: 32722760,
      capital: "Kuala Lumpur",
      area: 330803,
      currency: "Malaysischer Ringgit (MYR)",
    },
    geography: {
      region: "Asien",
      subregion: "Südostasien",
      borders: ["bn", "id", "th"],
      isIsland: false,
    },
  },
  {
    name: "Namibia",
    abbreviation: "na",
    flagSrc: "/flags/na.svg",
    facts: {
      population: 2540905,
      capital: "Windhoek",
      area: 825615,
      currency: "Namibischer Dollar (NAD), Südafrikanischer Rand (ZAR)",
    },
    geography: {
      region: "Afrika",
      subregion: "Südafrika",
      borders: ["ao", "bw", "za", "zm"],
      isIsland: false,
    },
  },
  {
    name: "New Caledonia",
    abbreviation: "nc",
    flagSrc: "/flags/nc.svg",
    facts: {
      population: 282750,
      capital: "Nouméa",
      area: 18575,
      currency: "CFP-Franc (XPF)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Melanesien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Niger",
    abbreviation: "ne",
    flagSrc: "/flags/ne.svg",
    facts: {
      population: 24206644,
      capital: "Niamey",
      area: 1267000,
      currency: "CFA-Franc (XOF)",
    },
    geography: {
      region: "Afrika",
      subregion: "Westafrika",
      borders: ["dz", "bj", "bf", "td", "ly", "mg", "mw", "ng"],
      isIsland: false,
    },
  },
  {
    name: "Mali",
    abbreviation: "ml",
    flagSrc: "/flags/ml.svg",
    facts: {
      population: 20250833,
      capital: "Bamako",
      area: 1240192,
      currency: "CFA-Franc (XOF)",
    },
    geography: {
      region: "Afrika",
      subregion: "Westafrika",
      borders: ["dz", "bf", "ne", "sn", "gm", "gn", "ci", "bf"],
      isIsland: false,
    },
  },
  {
    name: "Malta",
    abbreviation: "mt",
    flagSrc: "/flags/mt.svg",
    facts: {
      population: 514564,
      capital: "Valletta",
      area: 316,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Europa",
      subregion: "Südeuropa",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Myanmar",
    abbreviation: "mm",
    flagSrc: "/flags/mm.svg",
    facts: {
      population: 54409800,
      capital: "Naypyidaw",
      area: 676578,
      currency: "Myanmarischer Kyat (MMK)",
    },
    geography: {
      region: "Asien",
      subregion: "Südostasien",
      borders: ["bd", "cn", "in", "la", "th"],
      isIsland: false,
    },
  },
  {
    name: "Montenegro",
    abbreviation: "me",
    flagSrc: "/flags/me.svg",
    facts: {
      population: 622359,
      capital: "Podgorica",
      area: 13812,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Europa",
      subregion: "Südeuropa",
      borders: ["al", "ba", "hr", "rs"],
      isIsland: false,
    },
  },
  {
    name: "Mongolia",
    abbreviation: "mn",
    flagSrc: "/flags/mn.svg",
    facts: {
      population: 3225167,
      capital: "Ulan-Bator",
      area: 1564110,
      currency: "Mongolischer Tögrög (MNT)",
    },
    geography: {
      region: "Asien",
      subregion: "Ostasien",
      borders: ["cn", "ru"],
      isIsland: false,
    },
  },
  {
    name: "Northern Mariana Islands",
    abbreviation: "mp",
    flagSrc: "/flags/mp.svg",
    facts: {
      population: 57559,
      capital: "Saipan",
      area: 464,
      currency: "US-Dollar (USD)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Mikronesien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Mozambique",
    abbreviation: "mz",
    flagSrc: "/flags/mz.svg",
    facts: {
      population: 31255435,
      capital: "Maputo",
      area: 801590,
      currency: "Mosambikanischer Metical (MZN)",
    },
    geography: {
      region: "Afrika",
      subregion: "Ostafrika",
      borders: ["sz", "za", "tz", "zm", "zw"],
      isIsland: false,
    },
  },
  {
    name: "Mauritania",
    abbreviation: "mr",
    flagSrc: "/flags/mr.svg",
    facts: {
      population: 4403319,
      capital: "Nouakchott",
      area: 1030700,
      currency: "Ouguiya (MRU)",
    },
    geography: {
      region: "Afrika",
      subregion: "Westafrika",
      borders: ["dz", "ml", "sn", "eh"],
      isIsland: false,
    },
  },
  {
    name: "Montserrat",
    abbreviation: "ms",
    flagSrc: "/flags/ms.svg",
    facts: {
      population: 4992,
      capital: "Plymouth (de jure), Brades (de facto)",
      area: 102,
      currency: "Ostkaribischer Dollar (XCD)",
    },
    geography: {
      region: "Amerika",
      subregion: "Karibik",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Martinique",
    abbreviation: "mq",
    flagSrc: "/flags/mq.svg",
    facts: {
      population: 376480,
      capital: "Fort-de-France",
      area: 1128,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Amerika",
      subregion: "Karibik",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Mauritius",
    abbreviation: "mu",
    flagSrc: "/flags/mu.svg",
    facts: {
      population: 1271768,
      capital: "Port Louis",
      area: 2040,
      currency: "Mauritius-Rupie (MUR)",
    },
    geography: {
      region: "Afrika",
      subregion: "Ostafrika",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Maldives",
    abbreviation: "mv",
    flagSrc: "/flags/mv.svg",
    facts: {
      population: 515696,
      capital: "Malé",
      area: 300,
      currency: "Malediven-Rufiyaa (MVR)",
    },
    geography: {
      region: "Asien",
      subregion: "Südasien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Malawi",
    abbreviation: "mw",
    flagSrc: "/flags/mw.svg",
    facts: {
      population: 19129952,
      capital: "Lilongwe",
      area: 118484,
      currency: "Malawischer Kwacha (MWK)",
    },
    geography: {
      region: "Afrika",
      subregion: "Ostafrika",
      borders: ["mz", "tz", "zm"],
      isIsland: false,
    },
  },
  {
    name: "Mexico",
    abbreviation: "mx",
    flagSrc: "/flags/mx.svg",
    facts: {
      population: 126190788,
      capital: "Mexiko-Stadt",
      area: 1964375,
      currency: "Mexikanischer Peso (MXN)",
    },
    geography: {
      region: "Amerika",
      subregion: "Zentralamerika",
      borders: ["bz", "gt", "us"],
      isIsland: false,
    },
  },
  {
    name: "Malaysia",
    abbreviation: "my",
    flagSrc: "/flags/my.svg",
    facts: {
      population: 32722760,
      capital: "Kuala Lumpur",
      area: 330803,
      currency: "Malaysischer Ringgit (MYR)",
    },
    geography: {
      region: "Asien",
      subregion: "Südostasien",
      borders: ["bn", "id", "th"],
      isIsland: false,
    },
  },
  {
    name: "Namibia",
    abbreviation: "na",
    flagSrc: "/flags/na.svg",
    facts: {
      population: 2540905,
      capital: "Windhoek",
      area: 825615,
      currency: "Namibischer Dollar (NAD), Südafrikanischer Rand (ZAR)",
    },
    geography: {
      region: "Afrika",
      subregion: "Südafrika",
      borders: ["ao", "bw", "za", "zm"],
      isIsland: false,
    },
  },
  {
    name: "New Caledonia",
    abbreviation: "nc",
    flagSrc: "/flags/nc.svg",
    facts: {
      population: 282750,
      capital: "Nouméa",
      area: 18575,
      currency: "CFP-Franc (XPF)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Melanesien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Niger",
    abbreviation: "ne",
    flagSrc: "/flags/ne.svg",
    facts: {
      population: 24206644,
      capital: "Niamey",
      area: 1267000,
      currency: "CFA-Franc (XOF)",
    },
    geography: {
      region: "Afrika",
      subregion: "Westafrika",
      borders: ["dz", "bj", "bf", "td", "ly", "mg", "mw", "ng"],
      isIsland: false,
    },
  },
  {
    name: "Norfolk Island",
    abbreviation: "nf",
    flagSrc: "/flags/nf.svg",
    facts: {
      population: 1748,
      capital: "Kingston",
      area: 36,
      currency: "Australischer Dollar (AUD)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Australien und Neuseeland",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Nigeria",
    abbreviation: "ng",
    flagSrc: "/flags/ng.svg",
    facts: {
      population: 206139589,
      capital: "Abuja",
      area: 923768,
      currency: "Nigerianischer Naira (NGN)",
    },
    geography: {
      region: "Afrika",
      subregion: "Westafrika",
      borders: ["bj", "cm", "td", "ne"],
      isIsland: false,
    },
  },
  {
    name: "Nicaragua",
    abbreviation: "ni",
    flagSrc: "/flags/ni.svg",
    facts: {
      population: 6624554,
      capital: "Managua",
      area: 130373,
      currency: "Nicaraguanischer Córdoba (NIO)",
    },
    geography: {
      region: "Amerika",
      subregion: "Zentralamerika",
      borders: ["cr", "hn"],
      isIsland: false,
    },
  },
  {
    name: "Netherlands",
    abbreviation: "nl",
    flagSrc: "/flags/nl.svg",
    facts: {
      population: 17134872,
      capital: "Amsterdam",
      area: 41850,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Europa",
      subregion: "Westeuropa",
      borders: ["be", "de"],
      isIsland: false,
    },
  },
  {
    name: "Norway",
    abbreviation: "no",
    flagSrc: "/flags/no.svg",
    facts: {
      population: 5421241,
      capital: "Oslo",
      area: 323802,
      currency: "Norwegische Krone (NOK)",
    },
    geography: {
      region: "Europa",
      subregion: "Nordeuropa",
      borders: ["fi", "se", "ru"],
      isIsland: false,
    },
  },
  {
    name: "Nepal",
    abbreviation: "np",
    flagSrc: "/flags/np.svg",
    facts: {
      population: 29136808,
      capital: "Kathmandu",
      area: 147516,
      currency: "Nepalesische Rupie (NPR)",
    },
    geography: {
      region: "Asien",
      subregion: "Südasien",
      borders: ["cn", "in"],
      isIsland: false,
    },
  },
  {
    name: "Nauru",
    abbreviation: "nr",
    flagSrc: "/flags/nr.svg",
    facts: {
      population: 10824,
      capital: "Yaren",
      area: 21,
      currency: "Australischer Dollar (AUD)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Mikronesien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Niue",
    abbreviation: "nu",
    flagSrc: "/flags/nu.svg",
    facts: {
      population: 1615,
      capital: "Alofi",
      area: 260,
      currency: "Neuseeland-Dollar (NZD)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Polynesien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "New Zealand",
    abbreviation: "nz",
    flagSrc: "/flags/nz.svg",
    facts: {
      population: 4822233,
      capital: "Wellington",
      area: 270467,
      currency: "Neuseeland-Dollar (NZD)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Australien und Neuseeland",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Oman",
    abbreviation: "om",
    flagSrc: "/flags/om.svg",
    facts: {
      population: 5106622,
      capital: "Maskat",
      area: 309500,
      currency: "Omanischer Rial (OMR)",
    },
    geography: {
      region: "Asien",
      subregion: "Westasien",
      borders: ["sa", "ae", "ye"],
      isIsland: false,
    },
  },
  {
    name: "Panama",
    abbreviation: "pa",
    flagSrc: "/flags/pa.svg",
    facts: {
      population: 4314767,
      capital: "Panama-Stadt",
      area: 75417,
      currency: "Balboa und US-Dollar (PAB, USD)",
    },
    geography: {
      region: "Amerika",
      subregion: "Zentralamerika",
      borders: ["co", "cr"],
      isIsland: false,
    },
  },
  {
    name: "Peru",
    abbreviation: "pe",
    flagSrc: "/flags/pe.svg",
    facts: {
      population: 32971846,
      capital: "Lima",
      area: 1285216,
      currency: "Peruanischer Sol (PEN)",
    },
    geography: {
      region: "Amerika",
      subregion: "Südamerika",
      borders: ["bo", "br", "cl", "co", "ec"],
      isIsland: false,
    },
  },
  {
    name: "French Polynesia",
    abbreviation: "pf",
    flagSrc: "/flags/pf.svg",
    facts: {
      population: 280908,
      capital: "Papeete",
      area: 4167,
      currency: "CFP-Franc (XPF)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Polynesien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Papua New Guinea",
    abbreviation: "pg",
    flagSrc: "/flags/pg.svg",
    facts: {
      population: 8947024,
      capital: "Port Moresby",
      area: 462840,
      currency: "Papua-Neuguinea-Kina (PGK)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Melanesien",
      borders: ["id"],
      isIsland: true,
    },
  },
  {
    name: "Philippines",
    abbreviation: "ph",
    flagSrc: "/flags/ph.svg",
    facts: {
      population: 109581078,
      capital: "Manila",
      area: 342353,
      currency: "Philippinischer Peso (PHP)",
    },
    geography: {
      region: "Asien",
      subregion: "Südostasien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Pakistan",
    abbreviation: "pk",
    flagSrc: "/flags/pk.svg",
    facts: {
      population: 220892331,
      capital: "Islamabad",
      area: 881913,
      currency: "Pakistanische Rupie (PKR)",
    },
    geography: {
      region: "Asien",
      subregion: "Südasien",
      borders: ["af", "cn", "in", "ir"],
      isIsland: false,
    },
  },
  {
    name: "Poland",
    abbreviation: "pl",
    flagSrc: "/flags/pl.svg",
    facts: {
      population: 38386000,
      capital: "Warschau",
      area: 312696,
      currency: "Polnischer Złoty (PLN)",
    },
    geography: {
      region: "Europa",
      subregion: "Osteuropa",
      borders: ["by", "cz", "de", "lt", "ru", "sk", "ua"],
      isIsland: false,
    },
  },
  {
    name: "Saint Pierre and Miquelon",
    abbreviation: "pm",
    flagSrc: "/flags/pm.svg",
    facts: {
      population: 6008,
      capital: "Saint-Pierre",
      area: 242,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Amerika",
      subregion: "Nordamerika",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Pitcairn",
    abbreviation: "pn",
    flagSrc: "/flags/pn.svg",
    facts: {
      population: 47,
      capital: "Adamstown",
      area: 47,
      currency: "Neuseeland-Dollar (NZD)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Polynesien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Pitcairn Islands",
    abbreviation: "pn",
    flagSrc: "/flags/pn.svg",
    facts: {
      population: 47,
      capital: "Adamstown",
      area: 47,
      currency: "Neuseeland-Dollar (NZD)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Polynesien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Puerto Rico",
    abbreviation: "pr",
    flagSrc: "/flags/pr.svg",
    facts: {
      population: 3193694,
      capital: "San Juan",
      area: 8870,
      currency: "US-Dollar (USD)",
    },
    geography: {
      region: "Amerika",
      subregion: "Karibik",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Palestine",
    abbreviation: "ps",
    flagSrc: "/flags/ps.svg",
    facts: {
      population: 5000000,
      capital: "East Jerusalem",
      area: 6220,
      currency: "Israelischer Schekel (ILS)",
    },
    geography: {
      region: "Asien",
      subregion: "Westasien",
      borders: ["il", "jo"],
      isIsland: false,
    },
  },
  {
    name: "Portugal",
    abbreviation: "pt",
    flagSrc: "/flags/pt.svg",
    facts: {
      population: 10196709,
      capital: "Lissabon",
      area: 92090,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Europa",
      subregion: "Südeuropa",
      borders: ["es"],
      isIsland: false,
    },
  },
  {
    name: "Palau",
    abbreviation: "pw",
    flagSrc: "/flags/pw.svg",
    facts: {
      population: 18094,
      capital: "Ngerulmud",
      area: 459,
      currency: "US-Dollar (USD)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Mikronesien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Paraguay",
    abbreviation: "py",
    flagSrc: "/flags/py.svg",
    facts: {
      population: 7132530,
      capital: "Asunción",
      area: 406752,
      currency: "Paraguayischer Guaraní (PYG)",
    },
    geography: {
      region: "Amerika",
      subregion: "Südamerika",
      borders: ["ar", "bo", "br"],
      isIsland: false,
    },
  },
  {
    name: "Qatar",
    abbreviation: "qa",
    flagSrc: "/flags/qa.svg",
    facts: {
      population: 2881053,
      capital: "Doha",
      area: 11586,
      currency: "Katar-Riyal (QAR)",
    },
    geography: {
      region: "Asien",
      subregion: "Westasien",
      borders: ["sa"],
      isIsland: false,
    },
  },
  {
    name: "Réunion",
    abbreviation: "re",
    flagSrc: "/flags/re.svg",
    facts: {
      population: 859959,
      capital: "Saint-Denis",
      area: 2511,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Afrika",
      subregion: "Östliches Afrika",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Romania",
    abbreviation: "ro",
    flagSrc: "/flags/ro.svg",
    facts: {
      population: 19237691,
      capital: "Bukarest",
      area: 238397,
      currency: "Rumänischer Leu (RON)",
    },
    geography: {
      region: "Europa",
      subregion: "Osteuropa",
      borders: ["bg", "hu", "md", "rs", "ua"],
      isIsland: false,
    },
  },
  {
    name: "Serbia",
    abbreviation: "rs",
    flagSrc: "/flags/rs.svg",
    facts: {
      population: 8772235,
      capital: "Belgrad",
      area: 88361,
      currency: "Serbischer Dinar (RSD)",
    },
    geography: {
      region: "Europa",
      subregion: "Südosteuropa",
      borders: ["ba", "bg", "hr", "hu", "me", "mk", "ro"],
      isIsland: false,
    },
  },
  {
    name: "Russia",
    abbreviation: "ru",
    flagSrc: "/flags/ru.svg",
    facts: {
      population: 145912025,
      capital: "Moskau",
      area: 17098242,
      currency: "Russischer Rubel (RUB)",
    },
    geography: {
      region: "Europa und Asien",
      subregion: "Osteuropa und Nördliches Asien",
      borders: ["az", "by", "cn", "ee", "fi", "ge", "kz", "kp", "lt", "lv", "mn", "no", "pl", "ua"],
      isIsland: false,
    },
  },
  {
    name: "Rwanda",
    abbreviation: "rw",
    flagSrc: "/flags/rw.svg",
    facts: {
      population: 12952218,
      capital: "Kigali",
      area: 26338,
      currency: "Ruanda-Franc (RWF)",
    },
    geography: {
      region: "Afrika",
      subregion: "Ostafrika",
      borders: ["bi", "cd", "tz", "ug"],
      isIsland: false,
    },
  },
  {
    name: "Saudi Arabia",
    abbreviation: "sa",
    flagSrc: "/flags/sa.svg",
    facts: {
      population: 34813871,
      capital: "Riad",
      area: 2149690,
      currency: "Saudi-Riyal (SAR)",
    },
    geography: {
      region: "Asien",
      subregion: "Westasien",
      borders: ["iq", "jo", "kw", "om", "qa", "ae", "ye"],
      isIsland: false,
    },
  },
  {
    name: "Solomon Islands",
    abbreviation: "sb",
    flagSrc: "/flags/sb.svg",
    facts: {
      population: 686884,
      capital: "Honiara",
      area: 28896,
      currency: "Salomonen-Dollar (SBD)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Melanesien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Seychelles",
    abbreviation: "sc",
    flagSrc: "/flags/sc.svg",
    facts: {
      population: 98347,
      capital: "Victoria",
      area: 452,
      currency: "Seychellen-Rupie (SCR)",
    },
    geography: {
      region: "Afrika",
      subregion: "Ostafrika",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Sudan",
    abbreviation: "sd",
    flagSrc: "/flags/sd.svg",
    facts: {
      population: 43849260,
      capital: "Khartum",
      area: 1886068,
      currency: "Sudanesisches Pfund (SDG)",
    },
    geography: {
      region: "Afrika",
      subregion: "Nordafrika",
      borders: ["cf", "td", "eg", "er", "et", "ly", "ss"],
      isIsland: false,
    },
  },
  {
    name: "Sweden",
    abbreviation: "se",
    flagSrc: "/flags/se.svg",
    facts: {
      population: 10099265,
      capital: "Stockholm",
      area: 450295,
      currency: "Schwedische Krone (SEK)",
    },
    geography: {
      region: "Europa",
      subregion: "Nordeuropa",
      borders: ["fi", "no"],
      isIsland: false,
    },
  },
  {
    name: "Singapore",
    abbreviation: "sg",
    flagSrc: "/flags/sg.svg",
    facts: {
      population: 5850342,
      capital: "Singapur",
      area: 710,
      currency: "Singapur-Dollar (SGD)",
    },
    geography: {
      region: "Asien",
      subregion: "Südostasien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    abbreviation: "sh",
    flagSrc: "/flags/sh.svg",
    facts: {
      population: 5633,
      capital: "Jamestown",
      area: 394,
      currency: "St. Helena-Pfund (SHP)",
    },
    geography: {
      region: "Afrika",
      subregion: "Westafrika",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Slovenia",
    abbreviation: "si",
    flagSrc: "/flags/si.svg",
    facts: {
      population: 2078938,
      capital: "Ljubljana",
      area: 20273,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Europa",
      subregion: "Südeuropa",
      borders: ["at", "hr", "it", "hu"],
      isIsland: false,
    },
  },
  {
    name: "Svalbard and Jan Mayen",
    abbreviation: "sj",
    flagSrc: "/flags/sj.svg",
    facts: {
      population: 2655,
      capital: "Longyearbyen",
      area: 61399,
      currency: "Norwegische Krone (NOK)",
    },
    geography: {
      region: "Europa",
      subregion: "Nordeuropa",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Slovakia",
    abbreviation: "sk",
    flagSrc: "/flags/sk.svg",
    facts: {
      population: 5456362,
      capital: "Bratislava",
      area: 49037,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Europa",
      subregion: "Osteuropa",
      borders: ["at", "cz", "hu", "pl", "ua"],
      isIsland: false,
    },
  },
  {
    name: "Sierra Leone",
    abbreviation: "sl",
    flagSrc: "/flags/sl.svg",
    facts: {
      population: 7976983,
      capital: "Freetown",
      area: 71740,
      currency: "Sierra Leoneaner Leone (SLL)",
    },
    geography: {
      region: "Afrika",
      subregion: "Westafrika",
      borders: ["gn", "lr"],
      isIsland: false,
    },
  },
  {
    name: "San Marino",
    abbreviation: "sm",
    flagSrc: "/flags/sm.svg",
    facts: {
      population: 33931,
      capital: "San Marino",
      area: 61,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Europa",
      subregion: "Südeuropa",
      borders: ["it"],
      isIsland: false,
    },
  },
  {
    name: "Senegal",
    abbreviation: "sn",
    flagSrc: "/flags/sn.svg",
    facts: {
      population: 16743927,
      capital: "Dakar",
      area: 196722,
      currency: "CFA-Franc (XOF)",
    },
    geography: {
      region: "Afrika",
      subregion: "Westafrika",
      borders: ["gm", "gn", "ml", "mr"],
      isIsland: false,
    },
  },
  {
    name: "Somalia",
    abbreviation: "so",
    flagSrc: "/flags/so.svg",
    facts: {
      population: 15893222,
      capital: "Mogadischu",
      area: 637657,
      currency: "Somalia-Schilling (SOS)",
    },
    geography: {
      region: "Afrika",
      subregion: "Ostafrika",
      borders: ["dj", "et", "ke"],
      isIsland: false,
    },
  },
  {
    name: "Suriname",
    abbreviation: "sr",
    flagSrc: "/flags/sr.svg",
    facts: {
      population: 586632,
      capital: "Paramaribo",
      area: 163820,
      currency: "Suriname-Dollar (SRD)",
    },
    geography: {
      region: "Amerika",
      subregion: "Südamerika",
      borders: ["br", "gf", "gy"],
      isIsland: false,
    },
  },
  {
    name: "South Sudan",
    abbreviation: "ss",
    flagSrc: "/flags/ss.svg",
    facts: {
      population: 11193725,
      capital: "Juba",
      area: 619745,
      currency: "Südsudanesisches Pfund (SSP)",
    },
    geography: {
      region: "Afrika",
      subregion: "Ostafrika",
      borders: ["cd", "cf", "et", "ke", "sd", "ug"],
      isIsland: false,
    },
  },
  {
    name: "São Tomé and Príncipe",
    abbreviation: "st",
    flagSrc: "/flags/st.svg",
    facts: {
      population: 219159,
      capital: "São Tomé",
      area: 964,
      currency: "São Tomé und Príncipe Dobra (STN)",
    },
    geography: {
      region: "Afrika",
      subregion: "Zentralafrika",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "El Salvador",
    abbreviation: "sv",
    flagSrc: "/flags/sv.svg",
    facts: {
      population: 6486201,
      capital: "San Salvador",
      area: 21041,
      currency: "US-Dollar (USD)",
    },
    geography: {
      region: "Amerika",
      subregion: "Zentralamerika",
      borders: ["gt", "hn"],
      isIsland: false,
    },
  },
  {
    name: "Sint Maarten (Dutch part)",
    abbreviation: "sx",
    flagSrc: "/flags/sx.svg",
    facts: {
      population: 42388,
      capital: "Philipsburg",
      area: 34,
      currency: "Niederländischer Antillen-Gulden (ANG)",
    },
    geography: {
      region: "Amerika",
      subregion: "Karibik",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Syria",
    abbreviation: "sy",
    flagSrc: "/flags/sy.svg",
    facts: {
      population: 17500657,
      capital: "Damaskus",
      area: 185180,
      currency: "Syrisches Pfund (SYP)",
    },
    geography: {
      region: "Asien",
      subregion: "Westasien",
      borders: ["iq", "jo", "lb", "tr"],
      isIsland: false,
    },
  },
  {
    name: "Eswatini",
    abbreviation: "sz",
    flagSrc: "/flags/sz.svg",
    facts: {
      population: 1160164,
      capital: "Mbabane",
      area: 17364,
      currency: "Lilangeni (SZL) und Südafrikanischer Rand (ZAR)",
    },
    geography: {
      region: "Afrika",
      subregion: "Südafrika",
      borders: ["za", "mz"],
      isIsland: false,
    },
  },
  {
    name: "Turks and Caicos Islands",
    abbreviation: "tc",
    flagSrc: "/flags/tc.svg",
    facts: {
      population: 38191,
      capital: "Cockburn Town",
      area: 948,
      currency: "US-Dollar (USD)",
    },
    geography: {
      region: "Amerika",
      subregion: "Karibik",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Chad",
    abbreviation: "td",
    flagSrc: "/flags/td.svg",
    facts: {
      population: 16425864,
      capital: "N'Djamena",
      area: 1284000,
      currency: "CFA-Franc (XAF)",
    },
    geography: {
      region: "Afrika",
      subregion: "Zentralafrika",
      borders: ["cm", "cf", "ly", "ne", "ng", "sd"],
      isIsland: false,
    },
  },
  {
    name: "French Southern Territories",
    abbreviation: "tf",
    flagSrc: "/flags/tf.svg",
    facts: {
      population: 140,
      capital: "Port-aux-Français",
      area: 7747,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Antarktika",
      subregion: "Südlicher Ozean",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Togo",
    abbreviation: "tg",
    flagSrc: "/flags/tg.svg",
    facts: {
      population: 8278724,
      capital: "Lomé",
      area: 56785,
      currency: "CFA-Franc (XOF)",
    },
    geography: {
      region: "Afrika",
      subregion: "Westafrika",
      borders: ["bj", "bf", "gh"],
      isIsland: false,
    },
  },
  {
    name: "Thailand",
    abbreviation: "th",
    flagSrc: "/flags/th.svg",
    facts: {
      population: 69037513,
      capital: "Bangkok",
      area: 513120,
      currency: "Thailändischer Baht (THB)",
    },
    geography: {
      region: "Asien",
      subregion: "Südostasien",
      borders: ["kh", "la", "mm", "my"],
      isIsland: false,
    },
  },
  {
    name: "Tajikistan",
    abbreviation: "tj",
    flagSrc: "/flags/tj.svg",
    facts: {
      population: 9537645,
      capital: "Duschanbe",
      area: 143100,
      currency: "Somoni (TJS)",
    },
    geography: {
      region: "Asien",
      subregion: "Zentralasien",
      borders: ["af", "cn", "kg", "uz"],
      isIsland: false,
    },
  },
  {
    name: "Tokelau",
    abbreviation: "tk",
    flagSrc: "/flags/tk.svg",
    facts: {
      population: 1400,
      capital: "Nukunonu",
      area: 12,
      currency: "Neuseeland-Dollar (NZD)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Polynesien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Turkmenistan",
    abbreviation: "tm",
    flagSrc: "/flags/tm.svg",
    facts: {
      population: 6031187,
      capital: "Aschgabat",
      area: 488100,
      currency: "Turkmenistan-Manat (TMT)",
    },
    geography: {
      region: "Asien",
      subregion: "Zentralasien",
      borders: ["af", "ir", "kz", "uz"],
      isIsland: false,
    },
  },
  {
    name: "Timor-Leste",
    abbreviation: "tl",
    flagSrc: "/flags/tl.svg",
    facts: {
      population: 1318442,
      capital: "Dili",
      area: 14874,
      currency: "US-Dollar (USD), Timoresischer Escudo (TPE)",
    },
    geography: {
      region: "Asien",
      subregion: "Südostasien",
      borders: ["id"],
      isIsland: false,
    },
  },
  {
    name: "Tonga",
    abbreviation: "to",
    flagSrc: "/flags/to.svg",
    facts: {
      population: 105695,
      capital: "Nuku'alofa",
      area: 747,
      currency: "Tonganischer Pa'anga (TOP)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Polynesien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Trinidad and Tobago",
    abbreviation: "tt",
    flagSrc: "/flags/tt.svg",
    facts: {
      population: 1394973,
      capital: "Port of Spain",
      area: 5130,
      currency: "Trinidad und Tobago-Dollar (TTD)",
    },
    geography: {
      region: "Amerika",
      subregion: "Karibik",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Tunisia",
    abbreviation: "tn",
    flagSrc: "/flags/tn.svg",
    facts: {
      population: 11818619,
      capital: "Tunis",
      area: 163610,
      currency: "Tunesischer Dinar (TND)",
    },
    geography: {
      region: "Afrika",
      subregion: "Nordafrika",
      borders: ["dz", "ly"],
      isIsland: false,
    },
  },
  {
    name: "Turkey",
    abbreviation: "tr",
    flagSrc: "/flags/tr.svg",
    facts: {
      population: 83429615,
      capital: "Ankara",
      area: 783562,
      currency: "Türkische Lira (TRY)",
    },
    geography: {
      region: "Asien und Europa",
      subregion: "Westasien",
      borders: ["am", "az", "bg", "ge", "gr", "iq", "ir", "sy"],
      isIsland: false,
    },
  },
  {
    name: "Tuvalu",
    abbreviation: "tv",
    flagSrc: "/flags/tv.svg",
    facts: {
      population: 11792,
      capital: "Funafuti",
      area: 26,
      currency: "Australischer Dollar (AUD)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Polynesien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Taiwan, Province of China",
    abbreviation: "tw",
    flagSrc: "/flags/tw.svg",
    facts: {
      population: 23758247,
      capital: "Taipeh",
      area: 36193,
      currency: "Neuer Taiwan-Dollar (TWD)",
    },
    geography: {
      region: "Asien",
      subregion: "Ostasien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Tanzania, United Republic of",
    abbreviation: "tz",
    flagSrc: "/flags/tz.svg",
    facts: {
      population: 59734218,
      capital: "Dodoma",
      area: 945087,
      currency: "Tansania-Schilling (TZS)",
    },
    geography: {
      region: "Afrika",
      subregion: "Östliches Afrika",
      borders: ["bi", "cd", "ke", "mw", "mz", "rw", "ug", "zm"],
      isIsland: false,
    },
  },
  {
    name: "Ukraine",
    abbreviation: "ua",
    flagSrc: "/flags/ua.svg",
    facts: {
      population: 41590120,
      capital: "Kiew",
      area: 603500,
      currency: "Ukrainische Hrywnja (UAH)",
    },
    geography: {
      region: "Europa",
      subregion: "Osteuropa",
      borders: ["by", "hu", "md", "pl", "ro", "ru", "sk"],
      isIsland: false,
    },
  },
  {
    name: "Uganda",
    abbreviation: "ug",
    flagSrc: "/flags/ug.svg",
    facts: {
      population: 45741007,
      capital: "Kampala",
      area: 241550,
      currency: "Uganda-Schilling (UGX)",
    },
    geography: {
      region: "Afrika",
      subregion: "Ostafrika",
      borders: ["cd", "ke", "rw", "ss", "tz"],
      isIsland: false,
    },
  },
  {
    name: "United States Minor Outlying Islands",
    abbreviation: "um",
    flagSrc: "/flags/um.svg",
    facts: {
      population: 300,
      capital: "",
      area: 34.2,
      currency: "US-Dollar (USD)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Nordamerika",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "United States of America",
    abbreviation: "us",
    flagSrc: "/flags/us.svg",
    facts: {
      population: 331449281,
      capital: "Washington, D.C.",
      area: 9372610,
      currency: "US-Dollar (USD)",
    },
    geography: {
      region: "Amerika",
      subregion: "Nordamerika",
      borders: ["ca", "mx"],
      isIsland: false,
    },
  },
  {
    name: "Uruguay",
    abbreviation: "uy",
    flagSrc: "/flags/uy.svg",
    facts: {
      population: 3473727,
      capital: "Montevideo",
      area: 181034,
      currency: "Uruguayischer Peso (UYU)",
    },
    geography: {
      region: "Amerika",
      subregion: "Südamerika",
      borders: ["ar", "br"],
      isIsland: false,
    },
  },
  {
    name: "Uzbekistan",
    abbreviation: "uz",
    flagSrc: "/flags/uz.svg",
    facts: {
      population: 34169175,
      capital: "Taschkent",
      area: 447400,
      currency: "Usbekischer Som (UZS)",
    },
    geography: {
      region: "Asien",
      subregion: "Zentralasien",
      borders: ["af", "kz", "kg", "tj", "tm"],
      isIsland: false,
    },
  },
  {
    name: "Holy See (Vatican City State)",
    abbreviation: "va",
    flagSrc: "/flags/va.svg",
    facts: {
      population: 825,
      capital: "Vatikanstadt",
      area: 0.44,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Europa",
      subregion: "Südeuropa",
      borders: ["it"],
      isIsland: false,
    },
  },
  {
    name: "Saint Vincent and the Grenadines",
    abbreviation: "vc",
    flagSrc: "/flags/vc.svg",
    facts: {
      population: 110210,
      capital: "Kingstown",
      area: 389,
      currency: "Ostkaribischer Dollar (XCD)",
    },
    geography: {
      region: "Amerika",
      subregion: "Karibik",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Venezuela (Bolivarian Republic of)",
    abbreviation: "ve",
    flagSrc: "/flags/ve.svg",
    facts: {
      population: 28435940,
      capital: "Caracas",
      area: 916445,
      currency: "Venezolanischer Bolívar (VES)",
    },
    geography: {
      region: "Amerika",
      subregion: "Südamerika",
      borders: ["br", "co", "gy"],
      isIsland: false,
    },
  },
  {
    name: "British Virgin Islands",
    abbreviation: "vg",
    flagSrc: "/flags/vg.svg",
    facts: {
      population: 30237,
      capital: "Road Town",
      area: 151,
      currency: "US-Dollar (USD)",
    },
    geography: {
      region: "Amerika",
      subregion: "Karibik",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Virgin Islands (U.S.)",
    abbreviation: "vi",
    flagSrc: "/flags/vi.svg",
    facts: {
      population: 106405,
      capital: "Charlotte Amalie",
      area: 347,
      currency: "US-Dollar (USD)",
    },
    geography: {
      region: "Amerika",
      subregion: "Karibik",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Viet Nam",
    abbreviation: "vn",
    flagSrc: "/flags/vn.svg",
    facts: {
      population: 98168807,
      capital: "Hanoi",
      area: 331212,
      currency: "Dong (VND)",
    },
    geography: {
      region: "Asien",
      subregion: "Südostasien",
      borders: ["kh", "cn", "la"],
      isIsland: false,
    },
  },
  {
    name: "Vanuatu",
    abbreviation: "vu",
    flagSrc: "/flags/vu.svg",
    facts: {
      population: 307145,
      capital: "Port Vila",
      area: 12189,
      currency: "Vanuatu-Vatu (VUV)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Melanesien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Wallis and Futuna",
    abbreviation: "wf",
    flagSrc: "/flags/wf.svg",
    facts: {
      population: 11200,
      capital: "Mata-Utu",
      area: 142,
      currency: "CFP-Franc (XPF)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Polynesien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Samoa",
    abbreviation: "ws",
    flagSrc: "/flags/ws.svg",
    facts: {
      population: 200874,
      capital: "Apia",
      area: 2831,
      currency: "Samoanischer Tala (WST)",
    },
    geography: {
      region: "Ozeanien",
      subregion: "Polynesien",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "Yemen",
    abbreviation: "ye",
    flagSrc: "/flags/ye.svg",
    facts: {
      population: 29825964,
      capital: "Sanaa",
      area: 527968,
      currency: "Jemenitischer Rial (YER)",
    },
    geography: {
      region: "Asien",
      subregion: "Westasien",
      borders: ["om", "sa"],
      isIsland: false,
    },
  },
  {
    name: "Mayotte",
    abbreviation: "yt",
    flagSrc: "/flags/yt.svg",
    facts: {
      population: 272815,
      capital: "Mamoudzou",
      area: 374,
      currency: "Euro (EUR)",
    },
    geography: {
      region: "Afrika",
      subregion: "Östliches Afrika",
      borders: [],
      isIsland: true,
    },
  },
  {
    name: "South Africa",
    abbreviation: "za",
    flagSrc: "/flags/za.svg",
    facts: {
      population: 60041914,
      capital: "Pretoria, Kapstadt, Bloemfontein",
      area: 1221037,
      currency: "Südafrikanischer Rand (ZAR)",
    },
    geography: {
      region: "Afrika",
      subregion: "Südafrika",
      borders: ["bw", "ls", "mz", "na", "sz", "zw"],
      isIsland: false,
    },
  },
  {
    name: "Zambia",
    abbreviation: "zm",
    flagSrc: "/flags/zm.svg",
    facts: {
      population: 18383955,
      capital: "Lusaka",
      area: 752612,
      currency: "Sambischer Kwacha (ZMW)",
    },
    geography: {
      region: "Afrika",
      subregion: "Östliches Afrika",
      borders: ["ao", "bw", "cd", "mw", "mz", "na", "tz", "zw"],
      isIsland: false,
    },
  },
  {
    name: "Zimbabwe",
    abbreviation: "zw",
    flagSrc: "/flags/zw.svg",
    facts: {
      population: 14862924,
      capital: "Harare",
      area: 390757,
      currency:
        "Simbabwe-Dollar (ZWL), US-Dollar (USD), Südafrikanischer Rand (ZAR), Botswanischer Pula (BWP), Euro (EUR), Britisches Pfund (GBP), Indischer Rupie (INR), Chinesischer Yuan (CNY), Australischer Dollar (AUD)",
    },
    geography: {
      region: "Afrika",
      subregion: "Östliches Afrika",
      borders: ["bw", "mz", "za", "zm"],
      isIsland: false,
    },
  },
];
